[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
    'cd backend',
    'pip install -r requirements-railway.txt'
]

[start]
cmd = 'cd backend && python -m uvicorn app.main_railway:app --host 0.0.0.0 --port $PORT'