import type { Meta, StoryObj } from '@storybook/react'
import React from 'react'
import KiffResultConfigPage, { GeneratedFile } from './KiffResultConfigPage'

const meta: Meta<typeof KiffResultConfigPage> = {
  title: 'Kiffs/Result Config',
  component: KiffResultConfigPage,
  parameters: { layout: 'fullscreen' }
}

export default meta

type Story = StoryObj<typeof KiffResultConfigPage>

const sampleFiles: GeneratedFile[] = [
  {
    path: 'app/page.tsx',
    language: 'tsx',
    content: `export default function Page(){\n  return (<main className=\"p-8\">Hello from Kiff App</main>)\n}`
  },
  {
    path: 'components/Button.tsx',
    language: 'tsx',
    content: `export function Button({children}:{children:React.ReactNode}){\n  return <button className=\"rounded-full bg-slate-900 px-3 py-1.5 text-white\">{children}</button>\n}`
  },
  {
    path: 'README.md',
    language: 'md',
    content: `# Kiff App\n\nGenerated by Kiff Agent. Configure env and click Run.`
  }
]

export const Default: Story = {
  render: () => (
    <KiffResultConfigPage projectName="Demo Kiff App" files={sampleFiles} onRun={(env)=>console.log('run with env', env)} />
  )
}
